apiVersion: apps/v1
kind: Deployment
metadata:
  name: pearler-postgres
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pearler-database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pearler-database
    spec:
      containers:
        - name: pearler-database
          image: ${postgres_docker_image}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: PearlerDB
            - name: POSTGRES_USER
              value: PearlerDBUser
            - name: POSTGRES_PASSWORD
              value: "1234567821"
            
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pgdata
              name: postgresdb-data
            - mountPath: /docker-entrypoint-initdb.d
              name: postgresdb-init
      volumes:
        - name: postgresdb-data
          persistentVolumeClaim:
            claimName: pearler-postgres-pv-claim
        - name: postgresdb-init
          configMap:
            name: pearler-postgres-init