apiVersion: v1
kind: Service
metadata:
  namespace: ${namespace}
  name: pearler-database
spec:
  ports:
    - name: http
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: pearler-database