database:
  host: localhost
  port: 5432
  username: test
  password: lolkek
  database: postgres
server:
  host: localhost
  port: 3422
s3:
  endpoint: "https://storage.yandexcloud.net"
  bucket: "test-bucket"
  credentials:
    access_key_id: ""
    secret_access_key_path: "/cfg/secrets/s3_secret_access_key"